import React from 'react';
import LandingSection from './LandingSection';
import { Code, FormInput, Github, Key, KeyIcon, Server, WebhookIcon } from 'lucide-react';
import { ExternalLink } from 'lucide-react';
import FeatureCardTabs from './tabs/FeatureCardTabs';

const data = [
	{
		title: 'Web IDE & LSP',
		description: 'Python, Typescript, Go, Bash scripts with any dependencies',
		icon: Code,
		caption: 'Windmill supports Typescript, Python, Go and Bash scripts',
		video: {
			videoSrc: '/videos/languages.mp4',
			videoLength: 21
		}
	},

	{
		title: 'Autogenerated UI ',
		description:
			"Share your app with non-technical users without spending time building the UI. It's automatically generated from script parameters, and customizable.",
		icon: FormInput,
		caption: 'UI is autogenerated from script parameters',
		video: {
			videoSrc: '/videos/autogenerated-ui.mp4',
			videoLength: 26
		}
	},
	{
		title: 'Simple secret management',
		description:
			'Credentials and sensitive values are tightly permissioned and stored securely as secrets.',
		icon: Key,
		caption:
			'Secrets are stored securely and tightly permissioned, and can easily be inserted into scripts',
		video: {
			videoSrc: '/videos/secrets.mp4',
			videoLength: 44
		}
	}
];

const infrastructureData = [
	{
		title: 'Instant deployment',
		description:
			'Windmill is self-hosted, so you can run it on your own infrastructure. You can also run it on our cloud.',
		icon: Server,
		caption: 'Windmill is self-hosted, so you can run it on your own infrastructure',
		video: {
			videoSrc: '/videos/languages.mp4',
			videoLength: 44
		}
	},

	{
		title: 'Deployement from Github',
		description:
			'Windmill is horizontally scalable, so you can run as many scripts as you want. You can also run it on our cloud.',
		icon: Github,
		caption: 'Windmill is horizontally scalable, so you can run as many scripts as you want',
		video: {
			videoSrc: '/videos/languages.mp4',
			videoLength: 44
		}
	},
	{
		title: 'Versioned',
		description:
			'Each script is versioned with a unique hash, so you can easily rollback to a previous version if something goes wrong. ',
		icon: KeyIcon,
		caption: 'Each script is versioned with a unique hash',
		video: {
			videoSrc: '/videos/languages.mp4',
			videoLength: 44
		}
	}
];

const webhookData = [
	{
		title: 'Webhooks',
		description:
			'Windmill is self-hosted, so you can run it on your own infrastructure. You can also run it on our cloud.',
		icon: Server,
		caption: 'Windmill is self-hosted, so you can run it on your own infrastructure',
		video: {
			videoSrc: '/videos/languages.mp4',
			videoLength: 44
		}
	}
];

const tabs = [
	{
		label: 'Script Editor',
		icon: Code,
		id: 'script',
		data
	},
	{
		label: 'Infrastructure',
		icon: Server,
		id: 'infrastructure',
		data: infrastructureData
	},
	{
		label: 'Webhooks',
		icon: WebhookIcon,
		id: 'webhooks',
		data: webhookData
	}
];

export default function ScriptSection() {
	return (
		<LandingSection bgClass="bg-gradient-to-br from-white to-orange-50">
			<div className="flex flex-col gap-4 justify-center">
				<div className="flex flex-col gap-4 justify-center">
					<div className="flex-row gap-2 flex items-center">
						<h1 className="tracking-tight leading-tight text-left font-bold text-transparent bg-clip-text bg-gradient-to-br from-orange-400 to-orange-600">
							Apps
						</h1>

						<span className=" inline-flex items-center rounded-full bg-yellow-100 border-yellow-500 border px-3 py-0.5 text-sm font-medium text-yellow-800 mt-2">
							Alpha
						</span>
					</div>
					<h2 className="text-gray-600 text-2xl font-semibold">
						Build your own UI using our Wisiwig editor. Simply drag and drop components, connect
						your data and deploy your app in minutes.
					</h2>
				</div>

				<span className="text-lg text-gray-600 max-w-3xl">
					Develop and maintain scripts from our feature-complete webeditor or use your own IDE and
					deploy from Github. Upskill your less technical teammates. It's easier to learn writing
					useful scripts with Windmill.
				</span>

				<FeatureCardTabs tabs={tabs} color="orange" />

				<div className="flex">
					<a
						type="button"
						href="https://hub.windmill.dev/apps"
						target="_blank"
						className="inline-flex items-center rounded-md border border-transparent bg-orange-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 !no-underline hover:text-white"
					>
						Explore more apps on the Hub
						<ExternalLink className="ml-2 h-5" />
					</a>
				</div>
			</div>
		</LandingSection>
	);
}
