import React, { useState, useEffect, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { LayoutDashboard, Globe, Bot, SlidersHorizontal, Workflow, Clock, Webhook, Mail, Database, Radio, MessageSquare, Cloud, Rss, Zap} from 'lucide-react';

// ─── Use case data ───────────────────────────────────────────────────────────

const USE_CASES = [
	{ id: 'autoui', icon: SlidersHorizontal, label: 'Autogenerated UI', duration: 5500 },
	{ id: 'dag', icon: Workflow, label: 'Workflow engine', duration: 3500 },
	{ id: 'app', icon: LayoutDashboard, label: 'Custom frontend', duration: 3500 },
	{ id: 'agent', icon: Bot, label: 'AI agent', duration: 6000 },
	{ id: 'endpoint', icon: Zap, label: 'Triggers', duration: 2200 },
];

// ─── Shared DAG node component (light theme, matching workflow-automation) ───

const NODE_W = 160;
const NODE_H = 34;

// Inline logo components
function TsLogo() {
	return (
		<svg viewBox="0 0 256 256" className="w-4 h-4 flex-shrink-0">
			<rect width="256" height="256" rx="20" fill="#3178C6" />
			<path d="M150.518 200.475v27.62c4.492 2.302 9.805 4.028 15.938 5.179 6.133 1.151 12.597 1.726 19.393 1.726 6.622 0 12.914-.633 18.874-1.899 5.96-1.266 11.187-3.352 15.678-6.257 4.492-2.906 8.048-6.717 10.669-11.434 2.621-4.718 3.932-10.58 3.932-17.588 0-5.063-.882-9.493-2.647-13.29-1.766-3.796-4.175-7.19-7.229-10.18-3.054-2.99-6.622-5.694-10.707-8.113a165.4 165.4 0 0 0-13.207-7.16c-3.686-1.841-7.085-3.624-10.196-5.35-3.112-1.726-5.81-3.452-8.096-5.178-2.285-1.726-4.07-3.567-5.357-5.523-1.287-1.955-1.93-4.143-1.93-6.565 0-2.191.556-4.172 1.669-5.944 1.112-1.783 2.66-3.32 4.643-4.623 1.984-1.303 4.35-2.306 7.1-3.011 2.748-.704 5.752-1.056 9.01-1.056 2.401 0 4.905.187 7.514.561a60.5 60.5 0 0 1 7.921 1.726 51 51 0 0 1 7.661 2.905c2.459 1.151 4.718 2.507 6.778 4.069V109.25c-4.145-1.726-8.748-3.011-13.811-3.855-5.063-.843-10.94-1.265-17.632-1.265-6.535 0-12.74.705-18.614 2.114-5.874 1.41-11.04 3.624-15.496 6.645-4.457 3.02-7.978 6.89-10.563 11.607-2.585 4.718-3.877 10.349-3.877 16.894 0 8.344 2.488 15.504 7.463 21.481 4.976 5.977 12.371 10.953 22.186 14.928 3.86 1.553 7.463 3.107 10.81 4.661 3.345 1.554 6.245 3.195 8.697 4.921 2.452 1.726 4.378 3.624 5.78 5.694 1.4 2.07 2.1 4.431 2.1 7.085 0 2.016-.498 3.855-1.494 5.523-.997 1.668-2.436 3.107-4.319 4.316-1.882 1.21-4.175 2.133-6.878 2.77-2.703.636-5.752.954-9.147.954-5.98 0-11.842-1.063-17.585-3.188-5.744-2.124-10.882-5.34-15.414-9.646m-46.116-67.137h30.461v-25.27H65.063v25.27h30.318v86.572h24.066z" fill="#FFF" />
		</svg>
	);
}

function PyLogo() {
	return (
		<svg viewBox="0 0 256 255" className="w-4 h-4 flex-shrink-0">
			<defs>
				<linearGradient id="pyA" x1="12.96%" y1="12.07%" x2="79.68%" y2="78.21%">
					<stop offset="0%" stopColor="#387EB8" />
					<stop offset="100%" stopColor="#366994" />
				</linearGradient>
				<linearGradient id="pyB" x1="19.13%" y1="20.58%" x2="90.43%" y2="88.01%">
					<stop offset="0%" stopColor="#FFE052" />
					<stop offset="100%" stopColor="#FFC331" />
				</linearGradient>
			</defs>
			<path d="M126.916.072c-64.832 0-60.784 28.115-60.784 28.115l.072 29.128h61.868v8.745H41.631S.145 61.355.145 126.77c0 65.417 36.21 63.097 36.21 63.097h21.61v-30.356s-1.165-36.21 35.632-36.21h61.362s34.475.557 34.475-33.319V33.97S194.67.072 126.916.072ZM92.802 19.66a11.12 11.12 0 1 1 0 22.24 11.12 11.12 0 0 1 0-22.24Z" fill="url(#pyA)" />
			<path d="M128.757 254.126c64.832 0 60.784-28.115 60.784-28.115l-.072-29.127H127.6v-8.745h86.441s41.486 4.705 41.486-60.712c0-65.416-36.21-63.096-36.21-63.096h-21.61v30.355s1.165 36.21-35.632 36.21h-61.362s-34.475-.557-34.475 33.32v56.013s-5.235 33.897 62.518 33.897Zm34.114-19.586a11.12 11.12 0 1 1 0-22.24 11.12 11.12 0 0 1 0 22.24Z" fill="url(#pyB)" />
		</svg>
	);
}

function DuckDbLogo() {
	return (
		<img src="/third_party_logos/duckdb.svg" alt="DuckDB" className="w-4 h-4 flex-shrink-0" />
	);
}

function DuckLakeLogo() {
	return (
		<img src="/third_party_logos/ducklake.svg" alt="DuckLake" className="w-4 h-4 flex-shrink-0" />
	);
}

type DagNodeType = { label: string; x: number; y: number; isTs?: boolean; isPy?: boolean; isDuckDb?: boolean; isDuckLake?: boolean; isTrigger?: boolean; iconOnly?: boolean; isHighlighted?: boolean };

function DagNode({ node }: { node: DagNodeType }) {
	const bg = node.isHighlighted ? 'bg-blue-50' : node.isTrigger ? 'bg-blue-50' : 'bg-white';
	const border = node.isHighlighted ? 'border-blue-400' : node.isTrigger ? 'border-blue-200' : 'border-gray-200';
	const shadow = node.isHighlighted ? '0 0 12px rgba(59,130,246,0.35), 0 1px 2px rgba(0,0,0,0.05)' : undefined;

	if (node.iconOnly) {
		return (
			<div className="absolute" style={{ left: node.x, top: node.y, transform: 'translate(-50%, -50%)' }}>
				<div className={`flex items-center justify-center rounded-xl border ${border} ${bg} shadow-sm`} style={{ width: NODE_H, height: NODE_H, boxShadow: shadow }}>
					{node.isTs && <TsLogo />}
					{node.isPy && <PyLogo />}
					{node.isDuckDb && <DuckDbLogo />}
					{node.isDuckLake && <DuckLakeLogo />}
				</div>
			</div>
		);
	}

	return (
		<div className="absolute" style={{ left: node.x, top: node.y, transform: 'translate(-50%, -50%)' }}>
			<div className={`flex items-center justify-center gap-2 rounded-xl border ${border} ${bg} shadow-sm`} style={{ width: NODE_W, height: NODE_H, boxShadow: shadow }}>
				{node.isTs && <TsLogo />}
				{node.isPy && <PyLogo />}
				{node.isDuckDb && <DuckDbLogo />}
				{node.isDuckLake && <DuckLakeLogo />}
				{node.isTrigger && (
					<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="w-3.5 h-3.5 text-blue-500 flex-shrink-0">
						<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
					</svg>
				)}
				<span className={`text-[11px] font-medium whitespace-nowrap ${node.isHighlighted ? 'text-blue-700' : 'text-gray-700'}`}>{node.label}</span>
			</div>
		</div>
	);
}

// ─── Mini DAG animation (with 3 branches) ───────────────────────────────────

const CX = 280;
const B1 = 110, B2 = 280, B3 = 450; // 3 branch x-positions
const BY = 235;
const OY = 320; // Output node y

const DAG_NODES: DagNodeType[] = [
	{ label: 'Trigger', x: CX, y: 40, isTrigger: true },
	{ label: 'Input', x: CX, y: 100 },
	{ label: 'get_payments.ts', x: CX, y: 170, isTs: true, isHighlighted: true },
	{ label: 'Send email', x: B1, y: BY, isPy: true },
	{ label: 'Query DuckDB', x: B2, y: BY, isDuckDb: true },
	{ label: 'Archive', x: B3, y: BY, isDuckLake: true },
	{ label: 'Output', x: CX, y: OY },
];

function DagBall({ pathId, dur, delay, cycleDur }: { pathId: string; dur: number; delay: number; cycleDur: number }) {
	const [offset, setOffset] = useState(0);
	const [visible, setVisible] = useState(false);

	useEffect(() => {
		let frame: number;
		const start = performance.now();
		const animate = (now: number) => {
			const elapsed = ((now - start) / 1000) % cycleDur;
			const t = elapsed - delay;
			if (t >= 0 && t <= dur) {
				setOffset(t / dur);
				setVisible(true);
			} else {
				setVisible(false);
			}
			frame = requestAnimationFrame(animate);
		};
		frame = requestAnimationFrame(animate);
		return () => cancelAnimationFrame(frame);
	}, [dur, delay, cycleDur]);

	const pathEl = typeof document !== 'undefined' ? document.getElementById(pathId) as SVGPathElement | null : null;
	if (!pathEl || !visible) return null;
	const totalLen = pathEl.getTotalLength();
	const pt = pathEl.getPointAtLength(offset * totalLen);

	return (
		<circle cx={pt.x} cy={pt.y} r={5} className="fill-blue-400" style={{ filter: 'drop-shadow(0 0 6px rgba(96,165,250,0.8))' }} />
	);
}

const CYCLE_DUR = 7;
const TOP_DUR = 1.8;
const BRANCH_DUR = 1.5;
const BRANCH_DELAY = TOP_DUR + 0.2;
const MERGE_DUR = 1.5;
const MERGE_DELAY = BRANCH_DELAY + BRANCH_DUR + 0.2;

function MiniDag() {
	const branches = [B1, B2, B3];
	const midY = (170 + BY) / 2; // control point y for branching curves
	const mergeMidY = (BY + OY) / 2; // control point y for merging curves
	const [mounted, setMounted] = useState(false);
	useEffect(() => { setMounted(true); }, []);

	return (
		<div className="relative w-[560px] h-[350px] mx-auto mt-14" style={{ transform: 'scale(0.90)', transformOrigin: 'top center' }}>
			<svg className="absolute inset-0 w-full h-full" style={{ pointerEvents: 'none' }}>
				{/* Straight edges: Trigger → Input → get_payments */}
				<line x1={CX} y1={40 + NODE_H / 2} x2={CX} y2={100 - NODE_H / 2} className="stroke-gray-300" strokeWidth={1.5} />
				<line x1={CX} y1={100 + NODE_H / 2} x2={CX} y2={170 - NODE_H / 2} className="stroke-gray-300" strokeWidth={1.5} />
				{/* Branch-out curves: get_payments → branches */}
				{branches.map((bx, i) => (
					<React.Fragment key={`br-${i}`}>
						<path d={`M${CX},${170 + NODE_H / 2} C${CX},${midY} ${bx},${midY} ${bx},${BY - NODE_H / 2}`} className="stroke-gray-300" strokeWidth={1.5} fill="none" />
					</React.Fragment>
				))}
				{/* Merge curves: branches → Output */}
				{branches.map((bx, i) => (
					<React.Fragment key={`mg-${i}`}>
						<path d={`M${bx},${BY + NODE_H / 2} C${bx},${mergeMidY} ${CX},${mergeMidY} ${CX},${OY - NODE_H / 2}`} className="stroke-gray-300" strokeWidth={1.5} fill="none" />
					</React.Fragment>
				))}

				{/* Hidden paths for ball motion */}
				<path id="dag-top-path" d={`M${CX},${40 + NODE_H / 2} L${CX},${100 - NODE_H / 2} L${CX},${100 + NODE_H / 2} L${CX},${170 - NODE_H / 2}`} fill="none" stroke="none" />
				{branches.map((bx, i) => (
					<path key={`bp-${i}`} id={`dag-br-path-${i}`} d={`M${CX},${170 + NODE_H / 2} C${CX},${midY} ${bx},${midY} ${bx},${BY - NODE_H / 2}`} fill="none" stroke="none" />
				))}
				{branches.map((bx, i) => (
					<path key={`mp-${i}`} id={`dag-mg-path-${i}`} d={`M${bx},${BY + NODE_H / 2} C${bx},${mergeMidY} ${CX},${mergeMidY} ${CX},${OY - NODE_H / 2}`} fill="none" stroke="none" />
				))}

				{/* Animated balls */}
				{mounted && (
					<>
						<DagBall pathId="dag-top-path" dur={TOP_DUR} delay={0} cycleDur={CYCLE_DUR} />
						<DagBall pathId="dag-br-path-0" dur={BRANCH_DUR} delay={BRANCH_DELAY} cycleDur={CYCLE_DUR} />
						<DagBall pathId="dag-br-path-1" dur={BRANCH_DUR} delay={BRANCH_DELAY} cycleDur={CYCLE_DUR} />
						<DagBall pathId="dag-br-path-2" dur={BRANCH_DUR} delay={BRANCH_DELAY} cycleDur={CYCLE_DUR} />
						<DagBall pathId="dag-mg-path-0" dur={MERGE_DUR} delay={MERGE_DELAY} cycleDur={CYCLE_DUR} />
						<DagBall pathId="dag-mg-path-1" dur={MERGE_DUR} delay={MERGE_DELAY} cycleDur={CYCLE_DUR} />
						<DagBall pathId="dag-mg-path-2" dur={MERGE_DUR} delay={MERGE_DELAY} cycleDur={CYCLE_DUR} />
					</>
				)}
			</svg>
			{DAG_NODES.map((node, i) => <DagNode key={i} node={node} />)}
		</div>
	);
}

// ─── Mini internal app (Lottie dashboard) ───────────────────────────────────

function PlugBadge({ label, isGlowing }: { label: string; isGlowing: boolean }) {
	return (
		<motion.div
			className="flex items-center gap-1 rounded-md border px-1.5 py-0.5"
			animate={isGlowing
				? { borderColor: 'rgba(59,130,246,0.7)', backgroundColor: 'rgba(59,130,246,0.08)' }
				: { borderColor: 'rgba(209,213,219,0.5)', backgroundColor: 'transparent' }
			}
			transition={{ duration: 0.3 }}
		>
			<motion.div
				className="w-1.5 h-1.5 rounded-full"
				animate={isGlowing
					? { backgroundColor: 'rgb(96,165,250)', boxShadow: '0 0 4px rgba(96,165,250,0.8)' }
					: { backgroundColor: 'rgb(156,163,175)', boxShadow: '0 0 0px rgba(96,165,250,0)' }
				}
				transition={{ duration: 0.3 }}
			/>
			<span className="text-[8px] font-mono text-gray-400">{label}</span>
		</motion.div>
	);
}

function MiniApp() {
	const PULSE_INTERVAL = 1500;
	const [pulseIndex, setPulseIndex] = useState(0);
	const [isGlowing, setIsGlowing] = useState(false);

	useEffect(() => {
		const interval = setInterval(() => {
			setIsGlowing(true);
			setPulseIndex((prev) => prev + 1);
			setTimeout(() => setIsGlowing(false), 600);
		}, PULSE_INTERVAL);
		return () => clearInterval(interval);
	}, []);

	const stats = [
		{ label: 'Revenue', values: ['$12,340', '$12,580', '$12,920', '$13,100'], color: 'blue' },
		{ label: 'Users', values: ['1,205', '1,208', '1,215', '1,221'], color: 'green' },
		{ label: 'Active', values: ['847', '852', '861', '858'], color: 'amber' },
	];

	const barSets = [
		[18, 30, 22, 38, 28, 42, 35],
		[22, 28, 30, 35, 32, 38, 40],
		[20, 34, 25, 40, 30, 45, 32],
		[24, 26, 32, 36, 34, 40, 38],
	];
	const bars = barSets[pulseIndex % barSets.length];

	return (
		<div className="w-full max-w-[540px] mx-auto flex flex-col items-center px-4">
			{/* Frontend app mockup */}
			<div className="w-full rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden">
				{/* App title bar */}
				<div className="flex items-center px-3 py-1.5 bg-gray-50 border-b border-gray-200 gap-2">
					<div className="flex gap-1.5">
						<div className="w-2 h-2 rounded-full bg-red-400/60" />
						<div className="w-2 h-2 rounded-full bg-yellow-400/60" />
						<div className="w-2 h-2 rounded-full bg-green-400/60" />
					</div>
					<span className="text-[10px] text-gray-400 font-mono ml-1">Internal tool</span>
					<div className="flex items-center gap-1 ml-auto">
						{/* React (selected) */}
						<div className="flex items-center gap-1 rounded bg-blue-50 border border-blue-200 px-1.5 py-0.5">
							<svg viewBox="-11.5 -10.232 23 20.463" className="w-3 h-3">
								<circle r="2.05" fill="#61DAFB" />
								<g stroke="#61DAFB" strokeWidth="1" fill="none">
									<ellipse rx="11" ry="4.2" />
									<ellipse rx="11" ry="4.2" transform="rotate(60)" />
									<ellipse rx="11" ry="4.2" transform="rotate(120)" />
								</g>
							</svg>
							<span className="text-[8px] text-blue-600 font-medium">React</span>
						</div>
						{/* Svelte */}
						<div className="flex items-center gap-1 rounded bg-white border border-gray-200 px-1.5 py-0.5 opacity-50">
							<svg viewBox="0 0 98.1 118" className="w-3 h-3">
								<path d="M91.8 15.6C80.9-.5 59.2-4.7 43.6 5.2L16.1 22.8C8.6 27.5 3.4 35.2 1.9 43.9c-1.3 7.3-.2 14.8 3.3 21.3-2.4 3.6-4 7.6-4.7 11.8-1.6 8.9.5 18.1 5.7 25.4 11 16.1 32.7 20.3 48.2 10.4l27.5-17.6c7.5-4.7 12.7-12.4 14.2-21.1 1.3-7.3.2-14.8-3.3-21.3 2.4-3.6 4-7.6 4.7-11.8 1.7-9-.4-18.2-5.7-25.4" fill="#FF3E00" />
								<path d="M40.9 103.9a27.7 27.7 0 0 1-16.2-2.4A21.7 21.7 0 0 1 15 88.3c-1.4-5.2-.6-10.9 2.1-15.5l.6-1 .5-.9.8.6a38.3 38.3 0 0 0 11.6 6.1l1.1.4-.1 1a6.7 6.7 0 0 0 .8 3.8c.9 1.5 2.5 2.5 4.2 2.9a7.4 7.4 0 0 0 4.5-.5l27.5-17.6a6.2 6.2 0 0 0 2.8-3.9c.3-1.7-.2-3.5-1.4-4.8-.9-1.5-2.5-2.5-4.2-2.9a7.4 7.4 0 0 0-4.5.5l-10.5 6.7a22.9 22.9 0 0 1-14 1.6A21.7 21.7 0 0 1 26 52.3a20.7 20.7 0 0 1-2.2-14.8 19.5 19.5 0 0 1 8.5-12.2l27.5-17.6a22.9 22.9 0 0 1 14-1.6A21.7 21.7 0 0 1 83.5 19.3c1.4 5.2.6 10.9-2.1 15.5l-.6 1-.5.9-.8-.6a38.3 38.3 0 0 0-11.6-6.1l-1.1-.4.1-1a6.7 6.7 0 0 0-.8-3.8c-.9-1.5-2.5-2.5-4.2-2.9a7.4 7.4 0 0 0-4.5.5L30 40.1a6.2 6.2 0 0 0-2.8 3.9c-.3 1.7.2 3.5 1.4 4.8.9 1.5 2.5 2.5 4.2 2.9a7.4 7.4 0 0 0 4.5-.5l10.5-6.7a22.9 22.9 0 0 1 14-1.6 21.7 21.7 0 0 1 9.7 13.2 20.7 20.7 0 0 1 2.2 14.8 19.5 19.5 0 0 1-8.5 12.2l-27.5 17.6a22.3 22.3 0 0 1-6.8 3.2" fill="#FFF" />
							</svg>
						</div>
					</div>
				</div>
				<div className="p-2.5 space-y-2">
					{/* Stat cards */}
					<div className="grid grid-cols-3 gap-1.5">
						{stats.map((stat) => (
							<div key={stat.label} className={`rounded-lg bg-${stat.color}-50 border border-${stat.color}-100 px-2 py-1.5`}>
								<div className="flex items-center justify-between mb-0.5">
									<div className="text-[8px] text-gray-400">{stat.label}</div>

								</div>
								<motion.div
									key={`${stat.label}-${pulseIndex}`}
									className="text-[11px] font-semibold text-gray-700"
									initial={{ opacity: 0.5 }}
									animate={{ opacity: 1 }}
									transition={{ duration: 0.3 }}
								>
									{stat.values[pulseIndex % stat.values.length]}
								</motion.div>
							</div>
						))}
					</div>
					{/* Chart + Table side by side */}
					<div className="grid grid-cols-2 gap-1.5">
						{/* Mini bar chart */}
						<div className="rounded-lg border border-gray-100 p-2">
							<div className="flex items-center justify-between mb-1.5">
								<div className="text-[8px] text-gray-400">Monthly activity</div>

							</div>
							<svg viewBox="0 0 120 50" className="w-full h-[44px]">
								{bars.map((h, i) => (
									<motion.rect
										key={i}
										x={4 + i * 17}
										width={10}
										rx={2}
										animate={{ y: 50 - h, height: h }}
										transition={{ duration: 0.4, ease: 'easeOut' }}
										className={i === 5 ? 'fill-blue-400' : 'fill-blue-200'}
									/>
								))}
							</svg>
						</div>
						{/* Mini table */}
						<div className="rounded-lg border border-gray-100 p-2">
							<div className="flex items-center justify-between mb-1">
								<div className="text-[8px] text-gray-400">Table</div>

							</div>
							{[
								['Acme Corp', ['$4,200', '$4,350', '$4,500', '$4,480']],
								['Globex Inc', ['$3,100', '$3,100', '$3,250', '$3,300']],
								['Initech Ltd', ['$5,800', '$5,950', '$6,000', '$6,100']],
							].map(([name, amts], i) => (
								<div key={i} className={`grid grid-cols-3 text-[9px] py-0.5 ${i > 0 ? 'border-t border-gray-100' : ''}`}>
									<span className="text-gray-600">{name as string}</span>
									<motion.span
										key={`${name}-${pulseIndex}`}
										className="text-gray-500 text-center"
										initial={{ opacity: 0.5 }}
										animate={{ opacity: 1 }}
										transition={{ duration: 0.3 }}
									>
										{(amts as string[])[pulseIndex % (amts as string[]).length]}
									</motion.span>
									<span className={`text-right ${i !== 1 ? 'text-green-500' : 'text-amber-500'}`}>{i !== 1 ? 'Active' : 'Pending'}</span>
								</div>
							))}
						</div>
					</div>
					{/* Mini line chart */}
					<div className="rounded-lg border border-gray-100 p-2">
						<div className="flex items-center justify-between mb-1">
							<div className="text-[8px] text-gray-400">Trend</div>
							<PlugBadge label="get_payments" isGlowing={isGlowing} />
						</div>
						<svg viewBox="0 0 200 36" className="w-full h-[32px]">
							<polyline points="0,30 20,26 40,28 60,20 80,22 100,14 120,16 140,10 160,12 180,6 200,8" fill="none" className="stroke-blue-300" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
							<polyline points="0,30 20,26 40,28 60,20 80,22 100,14 120,16 140,10 160,12 180,6 200,8" fill="url(#lineGrad)" stroke="none" />
							<defs>
								<linearGradient id="lineGrad" x1="0" y1="0" x2="0" y2="1">
									<stop offset="0%" stopColor="rgb(147,197,253)" stopOpacity="0.3" />
									<stop offset="100%" stopColor="rgb(147,197,253)" stopOpacity="0" />
								</linearGradient>
							</defs>
						</svg>
					</div>
				</div>
			</div>

		</div>
	);
}

// ─── Mini endpoint ──────────────────────────────────────────────────────────

const TRIGGERS = [
	{ icon: Clock, label: 'Schedule' },
	{ icon: Webhook, label: 'Webhook' },
	{ icon: Mail, label: 'Email' },
	{ icon: Database, label: 'Postgres' },
	{ icon: Globe, label: 'HTTP routes' },
	{ icon: Radio, label: 'WebSocket' },
	{ icon: MessageSquare, label: 'Kafka' },
	{ icon: Rss, label: 'NATS' },
	{ icon: Cloud, label: 'SQS' },
	{ icon: Radio, label: 'MQTT' },
	{ icon: Cloud, label: 'GCP Pub/Sub' },
	{ icon: Bot, label: 'MCP' },
];

// ─── Mini Parameters UI (matches main function: resource: string, status: string, days: number) ──

function MiniAutoUI() {
	const CYCLE = 8;
	const [time, setTime] = useState(0);
	useEffect(() => {
		let frame: number;
		const start = performance.now();
		const tick = (now: number) => { setTime(((now - start) / 1000) % CYCLE); frame = requestAnimationFrame(tick); };
		frame = requestAnimationFrame(tick);
		return () => cancelAnimationFrame(frame);
	}, []);

	// Timeline: resource dropdown → select stripe_prod → status dropdown → select failed → fill days → run
	const dropdownOpen = time >= 1.2 && time < 2.8;
	const resourceSelected = time >= 2.8;
	const statusDropdownOpen = time >= 3.0 && time < 3.8;
	const statusSelected = time >= 3.8;
	const daysFilled = time >= 4.5;
	const runGlow = time >= 5.2;

	return (
		<div className="w-full max-w-[540px] mx-auto flex flex-col gap-4 px-4 py-4">
			{/* Parameters form */}
			<div className="rounded-xl bg-gray-50 border border-gray-200 p-4 flex flex-col gap-4">
				{/* resource: string — dropdown select */}
				<div className="relative flex flex-col gap-1.5">
					<div className="flex items-center gap-2">
						<svg className="w-3.5 h-3.5 text-purple-500 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
							<path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" />
						</svg>
						<span className="text-[11px] text-gray-600">resource</span>
						<span className="text-[10px] text-purple-400 font-bold">stripe</span>
						<span className="text-[10px] text-gray-400 ml-auto">string</span>
					</div>
					<div className="h-8 rounded-lg bg-white border border-gray-200 px-2.5 flex items-center justify-between">
						{resourceSelected ? (
							<motion.span
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								className="text-[11px] text-gray-700 font-mono"
							>
								stripe_prod
							</motion.span>
						) : (
							<span className="text-[11px] text-gray-400">Select a resource...</span>
						)}
						<svg className="w-3.5 h-3.5 text-gray-400" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
							<path d="M3 5l3 3 3-3" strokeLinecap="round" strokeLinejoin="round" />
						</svg>
					</div>
					<AnimatePresence>
						{dropdownOpen && (
							<motion.div
								initial={{ opacity: 0, y: -4 }}
								animate={{ opacity: 1, y: 0 }}
								exit={{ opacity: 0, y: -4 }}
								transition={{ duration: 0.15 }}
								className="absolute top-full left-0 right-0 z-10 mt-1 rounded-lg bg-white border border-gray-200 shadow-lg overflow-hidden"
							>
								{[
									{ name: 'stripe_sandbox', active: false },
									{ name: 'stripe_prod', active: true },
								].map((opt, i) => (
									<motion.div
										key={opt.name}
										initial={{ opacity: 0, x: -8 }}
										animate={{ opacity: 1, x: 0 }}
										transition={{ delay: 0.1 + i * 0.1 }}
										className={`px-2.5 py-2 flex items-center gap-2 ${opt.active ? 'bg-blue-50' : ''}`}
									>
										<div className={`w-2 h-2 rounded-full ${opt.active ? 'bg-blue-500' : 'bg-gray-300'}`} />
										<span className="text-[11px] text-gray-700 font-mono">{opt.name}</span>
									</motion.div>
								))}
							</motion.div>
						)}
					</AnimatePresence>
				</div>

				{/* status: string — select */}
				<div className="relative flex flex-col gap-1.5">
					<div className="flex items-center gap-2">
						<span className="text-[11px] text-gray-600">status</span>
						<span className="text-[10px] text-gray-400 ml-auto">string</span>
					</div>
					<div className="h-8 rounded-lg bg-white border border-gray-200 px-2.5 flex items-center justify-between">
						{statusSelected ? (
							<motion.span
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								className="text-[11px] text-gray-700 font-mono"
							>
								failed
							</motion.span>
						) : (
							<span className="text-[11px] text-gray-400">Select a status...</span>
						)}
						<svg className="w-3.5 h-3.5 text-gray-400" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="1.5">
							<path d="M3 5l3 3 3-3" strokeLinecap="round" strokeLinejoin="round" />
						</svg>
					</div>
					<AnimatePresence>
						{statusDropdownOpen && (
							<motion.div
								initial={{ opacity: 0, y: -4 }}
								animate={{ opacity: 1, y: 0 }}
								exit={{ opacity: 0, y: -4 }}
								transition={{ duration: 0.15 }}
								className="absolute top-full left-0 right-0 z-10 mt-1 rounded-lg bg-white border border-gray-200 shadow-lg overflow-hidden"
							>
								{[
									{ name: 'succeeded', active: false },
									{ name: 'failed', active: true },
									{ name: 'pending', active: false },
								].map((opt, i) => (
									<motion.div
										key={opt.name}
										initial={{ opacity: 0, x: -8 }}
										animate={{ opacity: 1, x: 0 }}
										transition={{ delay: 0.1 + i * 0.1 }}
										className={`px-2.5 py-2 flex items-center gap-2 ${opt.active ? 'bg-blue-50' : ''}`}
									>
										<div className={`w-2 h-2 rounded-full ${opt.active ? 'bg-blue-500' : 'bg-gray-300'}`} />
										<span className="text-[11px] text-gray-700 font-mono">{opt.name}</span>
									</motion.div>
								))}
							</motion.div>
						)}
					</AnimatePresence>
				</div>

				{/* days: number */}
				<div className="flex flex-col gap-1.5">
					<div className="flex items-center gap-2">
						<span className="text-[11px] text-gray-600">days</span>
						<span className="text-[10px] text-gray-400 ml-auto">number</span>
					</div>
					<div className="h-8 rounded-lg bg-white border border-gray-200 px-2.5 flex items-center">
						{daysFilled ? (
							<motion.span
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								className="text-[11px] text-gray-700 font-mono"
							>
								7
							</motion.span>
						) : (
							<span className="text-[11px] text-gray-400">Enter a value...</span>
						)}
					</div>
				</div>

				{/* Run button */}
				<motion.div
					className="h-8 rounded-lg flex items-center justify-center gap-1.5 mt-1"
					animate={runGlow
						? { backgroundColor: 'rgba(37,99,235,1)', boxShadow: '0 0 16px rgba(59,130,246,0.5)' }
						: { backgroundColor: 'rgba(37,99,235,0.3)', boxShadow: '0 0 0px rgba(59,130,246,0)' }
					}
					transition={{ duration: 0.4 }}
				>
					<span className="text-[11px] text-white font-medium">Run</span>
				</motion.div>
			</div>
		</div>
	);
}

// ─── Mini AI Agent animation ─────────────────────────────────────────────────

function MiniAgent() {
	const REPLY_TEXT = '5 payments failed over the last 3 days, totaling $1,240.';
	const [showUserMsg, setShowUserMsg] = useState(false);
	const [showTool, setShowTool] = useState(false);
	const [toolDone, setToolDone] = useState(false);
	const [showReply, setShowReply] = useState(false);
	const [charsVisible, setCharsVisible] = useState(0);

	useEffect(() => {
		const t0 = setTimeout(() => setShowUserMsg(true), 300);
		const t1 = setTimeout(() => setShowTool(true), 1200);
		const t2 = setTimeout(() => setToolDone(true), 2400);
		const t3 = setTimeout(() => setShowReply(true), 3000);
		return () => { clearTimeout(t0); clearTimeout(t1); clearTimeout(t2); clearTimeout(t3); };
	}, []);

	useEffect(() => {
		if (!showReply || charsVisible >= REPLY_TEXT.length) return;
		const delay = 25 + Math.random() * 15;
		const t = setTimeout(() => setCharsVisible((c) => c + 1), delay);
		return () => clearTimeout(t);
	}, [showReply, charsVisible]);

	return (
		<div className="w-full max-w-[480px] mx-auto flex flex-col gap-3 px-4 py-5">
			{/* User message */}
			{showUserMsg && (
				<motion.div
					initial={{ opacity: 0, y: 8 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 0.25 }}
					className="flex justify-end"
				>
					<div className="bg-blue-600 text-white text-[13px] px-3.5 py-2 rounded-2xl rounded-br-md max-w-[80%]">
						How many payments failed recently?
					</div>
				</motion.div>
			)}

			{/* Agent reply area */}
			{showTool && (
				<motion.div
					initial={{ opacity: 0, y: 8 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 0.25 }}
					className="flex items-start gap-2.5"
				>
					<div className="w-7 h-7 rounded-full bg-blue-100 flex items-center justify-center shrink-0 mt-1">
						<Bot className="w-4 h-4 text-blue-600" />
					</div>
					<div className="flex flex-col gap-2 min-w-0">
						{/* Tool badge */}
						<div className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-gray-200 bg-gray-50 w-fit">
							<svg className="w-3 h-3 text-amber-500 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
								<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z" />
							</svg>
							<span className="text-[10px] text-gray-700 font-mono">get_payments</span>
							{toolDone ? (
								<motion.div initial={{ opacity: 0, scale: 0.5 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.2 }}>
									<svg className="w-3 h-3 text-green-500" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2">
										<path d="M3 8l3.5 3.5L13 5" strokeLinecap="round" strokeLinejoin="round" />
									</svg>
								</motion.div>
							) : (
								<motion.div
									className="w-3 h-3 rounded-full border-2 border-blue-400 border-t-transparent"
									animate={{ rotate: 360 }}
									transition={{ duration: 0.8, repeat: Infinity, ease: 'linear' }}
								/>
							)}
						</div>

						{/* Reply bubble */}
						{showReply && (
							<motion.div
								initial={{ opacity: 0, y: 4 }}
								animate={{ opacity: 1, y: 0 }}
								transition={{ duration: 0.25 }}
								className="bg-gray-100 text-[13px] text-gray-700 px-3.5 py-2.5 rounded-2xl rounded-tl-md leading-relaxed"
							>
								{REPLY_TEXT.slice(0, charsVisible)}
								{charsVisible < REPLY_TEXT.length && (
									<motion.span
										className="inline-block w-[2px] h-[14px] bg-blue-400 ml-[1px] align-middle"
										animate={{ opacity: [1, 0] }}
										transition={{ duration: 0.5, repeat: Infinity, repeatType: 'reverse' }}
									/>
								)}
							</motion.div>
						)}
					</div>
				</motion.div>
			)}
		</div>
	);
}

// ─── Mini Endpoint animation ─────────────────────────────────────────────────

function MiniEndpoint() {
	return (
		<div className="w-full max-w-[480px] mx-auto flex flex-col gap-4 px-4 py-4">
			{/* Endpoint route */}
			<div className="rounded-lg border border-gray-200 bg-gray-50 p-3">
				<div className="font-mono text-[11px] text-gray-400 mb-1">Endpoint</div>
				<div className="font-mono text-[13px]">
					<span className="text-gray-700">POST</span>
					<span className="text-gray-400"> /api/w/my_workspace/</span>
					<span className="text-blue-600 font-semibold">get_payments</span>
				</div>
			</div>

			{/* Triggers section */}
			<div>
				<div className="text-[11px] text-gray-500 font-medium uppercase tracking-wider mb-2 px-1">Triggers</div>
				<div className="grid grid-cols-3 gap-2">
					{TRIGGERS.map((trigger, i) => {
						const Icon = trigger.icon;
						return (
							<div
								key={`${trigger.label}-${i}`}
								className="flex items-center gap-2 rounded-lg border border-gray-200 bg-white px-3 py-2 shadow-sm"
							>
								<Icon className="w-4 h-4 flex-shrink-0 text-gray-400" />
								<span className="text-[11px] font-medium whitespace-nowrap text-gray-600">{trigger.label}</span>
							</div>
						);
					})}
				</div>
			</div>
		</div>
	);
}

// ─── Cycling use cases ──────────────────────────────────────────────────────

function TabBar({ items, activeIndex, onSelect }: { items: typeof USE_CASES; activeIndex: number; onSelect: (i: number) => void }) {
	const containerRef = useRef<HTMLDivElement>(null);
	const [pillStyle, setPillStyle] = useState({ left: 0, width: 0 });

	useEffect(() => {
		const container = containerRef.current;
		if (!container) return;
		const buttons = container.querySelectorAll<HTMLButtonElement>('[data-tab-btn]');
		const btn = buttons[activeIndex];
		if (!btn) return;
		setPillStyle({
			left: btn.offsetLeft,
			width: btn.offsetWidth,
		});
	}, [activeIndex]);

	return (
		<div ref={containerRef} className="relative flex items-center rounded-full bg-gray-100 border border-gray-200 p-1">
			<motion.div
				className="absolute top-1 bottom-1 rounded-full bg-white border border-gray-300 shadow-sm"
				animate={{ left: pillStyle.left, width: pillStyle.width }}
				transition={{ type: 'spring', stiffness: 400, damping: 30 }}
			/>
			{items.map((u, i) => (
				<button
					key={u.id}
					data-tab-btn
					onClick={() => onSelect(i)}
					className="relative z-10 flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-[11px] font-medium whitespace-nowrap transition-colors duration-200"
					style={{ color: i === activeIndex ? '#111827' : '#9ca3af' }}
				>
					{u.label}
				</button>
			))}
		</div>
	);
}

function UseCasesCycling() {
	const [activeIndex, setActiveIndex] = useState(0);

	useEffect(() => {
		if (activeIndex >= USE_CASES.length - 1) return;
		const timeout = setTimeout(() => {
			setActiveIndex((prev) => prev + 1);
		}, USE_CASES[activeIndex].duration);
		return () => clearTimeout(timeout);
	}, [activeIndex]);

	const previews: Record<string, React.ReactNode> = {
		dag: <MiniDag />,
		autoui: <MiniAutoUI />,
		app: <MiniApp />,
		agent: <MiniAgent />,
		endpoint: <MiniEndpoint />,
	};

	return (
		<div className="flex flex-col items-center justify-center w-full h-full">
			<div className="w-full overflow-hidden">
				<div className="flex justify-center pt-2 pb-1">
					<TabBar items={USE_CASES} activeIndex={activeIndex} onSelect={setActiveIndex} />
				</div>

				<AnimatePresence mode="wait">
					<motion.div
						key={activeIndex}
						initial={{ opacity: 0 }}
						animate={{ opacity: 1 }}
						exit={{ opacity: 0 }}
						transition={{ duration: 0.2 }}
						className="w-full flex items-center justify-center overflow-hidden"
						style={{ height: 320 }}
					>
						{previews[USE_CASES[activeIndex].id]}
					</motion.div>
				</AnimatePresence>
			</div>
		</div>
	);
}

// ─── Complete animation: IDE → use cases → deploy → monitoring ──────────────

type Phase = 'typing' | 'connect' | 'usecases' | 'ready' | 'pushing' | 'deploying' | 'monitoring';

function CompleteAnimation() {
	const [phase, setPhase] = useState<Phase>('typing');

	const comps = React.useMemo(() => {
		const mod = require('./HeroAnimation');
		return {
			TypingCode: mod.TypingCode,
			StaticCode: mod.StaticCode,
			LiveRunsScatter: mod.LiveRunsScatter,
			LiveResultJson: mod.LiveResultJson,
			LiveDatabase: mod.LiveDatabase,
			LiveFrontend: mod.LiveFrontend,
			DB_ROWS: mod.DB_ROWS,
		};
	}, []);

	const handleTypingComplete = useCallback(() => {
		setPhase('connect');
	}, []);

	const [connectPushed, setConnectPushed] = useState(false);
	useEffect(() => {
		if (phase === 'connect') {
			setConnectPushed(false);
			const pushT = setTimeout(() => setConnectPushed(true), 1800);
			const nextT = setTimeout(() => setPhase('usecases'), 2500);
			return () => { clearTimeout(pushT); clearTimeout(nextT); };
		}
	}, [phase]);
	// Total: 3500+4500+3500+3500+3500 = 18500
	const totalUseCasesDuration = USE_CASES.reduce((sum, uc) => sum + uc.duration, 0);
	useEffect(() => { if (phase === 'usecases') { const t = setTimeout(() => setPhase('ready'), totalUseCasesDuration); return () => clearTimeout(t); } }, [phase]);
	useEffect(() => { if (phase === 'ready') { const t = setTimeout(() => setPhase('pushing'), 1200); return () => clearTimeout(t); } }, [phase]);
	useEffect(() => { if (phase === 'pushing') { const t = setTimeout(() => setPhase('deploying'), 800); return () => clearTimeout(t); } }, [phase]);
	useEffect(() => { if (phase === 'deploying') { const t = setTimeout(() => setPhase('monitoring'), 1400); return () => clearTimeout(t); } }, [phase]);

	const [runCount, setRunCount] = useState(0);
	const [cycleKey, setCycleKey] = useState(0);
	useEffect(() => {
		if (phase !== 'monitoring') { setRunCount(0); return; }
		setRunCount(1);
		let count = 1;
		const interval = setInterval(() => {
			count++;
			setRunCount(count);
			if (count >= comps.DB_ROWS.length) clearInterval(interval);
		}, 1000);
		return () => clearInterval(interval);
	}, [phase, comps.DB_ROWS.length]);

	// Loop: restart after monitoring completes
	useEffect(() => {
		if (phase !== 'monitoring') return;
		const totalMonitoringTime = comps.DB_ROWS.length * 1000 + 2000;
		const t = setTimeout(() => {
			setCycleKey((k) => k + 1);
			setPhase('typing');
		}, totalMonitoringTime);
		return () => clearTimeout(t);
	}, [phase, comps.DB_ROWS.length]);

	const showCodeBody = phase === 'typing' || phase === 'connect';
	const showUseCases = phase === 'usecases' || phase === 'ready' || phase === 'pushing';
	const showMonitoring = phase === 'monitoring';
	const isDeploying = phase === 'deploying';

	return (
		<div className="w-full h-[440px] sm:h-[500px] flex flex-col items-center justify-center relative pb-2">
			{/* Deploying phase: centered spinning logo overlaid on top */}
			<AnimatePresence>
				{isDeploying && (
					<motion.div
						className="absolute inset-0 flex flex-col items-center justify-center z-20"
						initial={{ opacity: 0 }}
						animate={{ opacity: 1 }}
						exit={{ opacity: 0 }}
						transition={{ duration: 0.3 }}
					>
						<img src="/img/windmill.svg" alt="Windmill" className="w-16 h-16 sm:w-20 sm:h-20 animate-spin" style={{ animationDuration: '3s' }} />
						<motion.div
							initial={{ opacity: 0, y: 5 }}
							animate={{ opacity: 1, y: 0 }}
							transition={{ delay: 0.5, duration: 0.3 }}
							className="mt-4 flex items-center gap-2 text-green-400 font-medium text-sm"
						>
							<motion.svg width="16" height="16" viewBox="0 0 16 16" fill="none">
								<circle cx="8" cy="8" r="7" stroke="currentColor" strokeWidth="1.5" fill="none" />
								<motion.path d="M4.5 8 L7 10.5 L11.5 5.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} transition={{ duration: 0.4, delay: 0.6 }} />
							</motion.svg>
							<span>Deployment successful</span>
						</motion.div>
					</motion.div>
				)}
			</AnimatePresence>

			{/* IDE container: always mounted, fades out during deploying */}
			<motion.div
				className="w-full overflow-hidden border"
				initial={{ borderTopLeftRadius: 12, borderTopRightRadius: 12, borderBottomLeftRadius: 12, borderBottomRightRadius: 12, borderColor: '#1f2937', backgroundColor: '#0d1117', boxShadow: '0 25px 50px -12px rgb(0 0 0 / 0.25)' }}
				animate={isDeploying
					? { opacity: 0, scale: 0.95, borderTopLeftRadius: 12, borderTopRightRadius: 12, borderBottomLeftRadius: 12, borderBottomRightRadius: 12, borderColor: '#e5e7eb', backgroundColor: '#f9fafb', boxShadow: 'none' }
					: showCodeBody
						? { opacity: 1, scale: 1, borderTopLeftRadius: 12, borderTopRightRadius: 12, borderBottomLeftRadius: 12, borderBottomRightRadius: 12, borderColor: '#1f2937', backgroundColor: '#0d1117', boxShadow: '0 25px 50px -12px rgb(0 0 0 / 0.25)' }
						: { opacity: 1, scale: 1, borderTopLeftRadius: 12, borderTopRightRadius: 12, borderBottomLeftRadius: 12, borderBottomRightRadius: 12, borderColor: '#e5e7eb', backgroundColor: '#f9fafb', boxShadow: 'none' }
				}
				transition={{ duration: 0.5, ease: [0.4, 0, 0.2, 1] }}
			>
				{/* Title bar — always visible */}
				<motion.div
					className="flex items-center px-3 py-2 gap-2"
					initial={{ backgroundColor: '#161b22', borderBottomWidth: 1, borderBottomColor: '#1f2937' }}
					animate={showCodeBody
						? { backgroundColor: '#161b22', borderBottomWidth: 1, borderBottomColor: '#1f2937' }
						: { backgroundColor: '#f9fafb', borderBottomWidth: 1, borderBottomColor: '#e5e7eb' }
					}
					transition={{ duration: 0.5, ease: [0.4, 0, 0.2, 1] }}
					style={{ borderBottomStyle: 'solid' }}
				>
					<div className="flex items-center gap-1.5">
						{showCodeBody
							? <TsLogo />
							: <img src="/img/windmill.svg" alt="Windmill" className={`h-4 w-4 ${showMonitoring ? 'animate-spin' : ''}`} style={showMonitoring ? { animationDuration: '3s' } : undefined} />
						}
						<motion.span
							className="text-sm font-mono"
							animate={{ color: showCodeBody ? '#9ca3af' : '#374151' }}
							transition={{ duration: 0.5 }}
						>
							get_payments.ts
						</motion.span>
						<AnimatePresence>
							{showMonitoring && (
								<motion.span
									initial={{ opacity: 0 }}
									animate={{ opacity: 1 }}
									exit={{ opacity: 0 }}
									transition={{ duration: 0.3 }}
									className="text-sm text-gray-400 font-mono"
								>
									- Running on Windmill workers
								</motion.span>
							)}
						</AnimatePresence>
					</div>

					{/* Buttons and labels in title bar */}
					<AnimatePresence mode="wait">
						{showCodeBody && (
							<motion.button
								key="connect-btn"
								initial={{ opacity: 0, scale: 0.8 }}
								animate={{
									opacity: phase === 'typing' ? 0.5 : 1,
									scale: connectPushed ? 0.92 : 1,
								}}
								exit={{ opacity: 0, scale: 0.8 }}
								transition={{ duration: 0.2 }}
								className={`ml-auto px-4 py-1.5 rounded-md text-sm font-semibold flex items-center gap-1.5 ${
									phase === 'typing'
										? 'bg-gray-300 text-white cursor-not-allowed'
										: 'bg-blue-600 text-white shadow-sm shadow-blue-600/30'
								}`}
							>
								<img src="/img/windmill.svg" alt="" className="w-4 h-4" />
								Push to Windmill
							</motion.button>
						)}
						{showUseCases && (
							<motion.button
								key="deploy-btn"
								initial={{ opacity: 0, scale: 0.8 }}
								animate={{
									opacity: phase === 'usecases' ? 0.5 : 1,
									scale: phase === 'pushing' ? 0.92 : 1,
								}}
								exit={{ opacity: 0, scale: 0.8 }}
								transition={{ duration: 0.2 }}
								className={`ml-auto px-4 py-1.5 rounded-md text-sm font-semibold flex items-center gap-1.5 ${
									phase === 'usecases'
										? 'bg-gray-300 text-white cursor-not-allowed'
										: 'bg-blue-600 text-white shadow-sm shadow-blue-600/30'
								}`}
							>
								Deploy
							</motion.button>
						)}
					</AnimatePresence>

				</motion.div>

				{/* Content area — crossfades between code, use cases, and monitoring */}
				<div className="relative" style={{ height: 400 }}>
					<AnimatePresence mode="wait">
						{showCodeBody && (
							<motion.div
								key="code"
								className="absolute inset-0"
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								exit={{ opacity: 0 }}
								transition={{ duration: 0.3 }}
							>
								<div className="p-3 sm:p-4 min-h-[280px] sm:min-h-[300px] flex flex-col">
									{phase === 'typing' ? <comps.TypingCode key={cycleKey} onComplete={handleTypingComplete} /> : <comps.StaticCode />}
								</div>
							</motion.div>
						)}

						{showUseCases && (
							<motion.div
								key="usecases"
								className="absolute inset-x-0 top-0"
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								exit={{ opacity: 0 }}
								transition={{ duration: 0.3 }}
							>
								<UseCasesCycling key={cycleKey} />
							</motion.div>
						)}

						{showMonitoring && (
							<motion.div
								key="monitoring"
								className="absolute inset-0 overflow-hidden grid grid-cols-2 grid-rows-2 gap-2 p-2"
								initial={{ opacity: 0 }}
								animate={{ opacity: 1 }}
								exit={{ opacity: 0 }}
								transition={{ duration: 0.3 }}
							>
								<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.3, duration: 0.3 }} className="rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden flex flex-col">
									<div className="px-2.5 py-1.5 bg-gray-50 border-b border-gray-200 flex items-center gap-1.5 shrink-0"><div className="w-2 h-2 rounded-full bg-green-500" /><span className="text-sm text-gray-600 font-medium">Runs</span></div>
									<div className="p-2 flex-1 min-h-0 flex flex-col justify-center"><comps.LiveRunsScatter runCount={runCount} light /></div>
								</motion.div>
								<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4, duration: 0.3 }} className="rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden flex flex-col">
									<div className="px-2.5 py-1.5 bg-gray-50 border-b border-gray-200 flex items-center gap-1.5 shrink-0"><div className="w-2 h-2 rounded-full bg-purple-500" /><span className="text-sm text-gray-600 font-medium">Result</span></div>
									<div className="p-2 flex-1 min-h-0 flex flex-col justify-center overflow-hidden"><comps.LiveResultJson runCount={runCount} light /></div>
								</motion.div>
								<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.5, duration: 0.3 }} className="rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden flex flex-col">
									<div className="px-2.5 py-1.5 bg-gray-50 border-b border-gray-200 flex items-center gap-1.5 shrink-0"><div className="w-2 h-2 rounded-full bg-amber-500" /><span className="text-sm text-gray-600 font-medium">Database</span></div>
									<div className="p-2 flex-1 min-h-0 flex flex-col justify-center overflow-hidden"><comps.LiveDatabase runCount={runCount} light /></div>
								</motion.div>
								<motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6, duration: 0.3 }} className="rounded-xl border border-gray-200 bg-white shadow-sm overflow-hidden flex flex-col">
									<div className="px-2.5 py-1.5 bg-gray-50 border-b border-gray-200 flex items-center gap-1.5 shrink-0"><div className="w-2 h-2 rounded-full bg-cyan-500" /><span className="text-sm text-gray-600 font-medium">Audit logs</span></div>
									<div className="p-2 flex-1 min-h-0 flex flex-col overflow-hidden"><comps.LiveFrontend runCount={runCount} light /></div>
								</motion.div>
							</motion.div>
						)}
					</AnimatePresence>
				</div>
			</motion.div>

		</div>
	);
}

export default CompleteAnimation;
