import React from 'react';
import LandingSection from './LandingSection';
import CardsContainer from './cards/Cards';
import { Terminal } from 'lucide-react';

export default function DevScriptsSections() {
	return (
		<LandingSection bgClass="bg-gradient-to-br from-slate-800 to-black">
			<div className="flex flex-col w-full gap-4 justify-center" id="script-section">
				<div className="flex flex-col gap-2">
					<h1 className="tracking-tight leading-tight text-left font-bold text-transparent bg-clip-text bg-gradient-to-br from-emerald-200 to-emerald-400">
						Flow
					</h1>
					<h2 className="text-white text-2xl font-semibold">
						No overhead, scalable, self-hostable FaaS
					</h2>
				</div>

				<span className="text-lg text-white max-w-3xl">
					Run long-running heavy background jobs, script with complex dependencies, endpoints with
					high rpm or simple one-off tasks without any overhead. Trigger them from a webhook or the
					auto-generated UI and monitor them easily.
				</span>

				<CardsContainer
					key="flow-card"
					color="#00FF00"
					cards={[
						{
							title: 'Polyglot',
							subtitle: 'Write scripts in any language',

							Icon: Terminal,
							gridArea: 'md:col-span-2 md:row-span-6'
						},
						{
							title: 'Auto-generated UI',
							subtitle: 'Trigger scripts using the autogenerated UI',
							Icon: Terminal,
							gridArea: 'md:col-span-2 md:row-span-2'
						}
					]}
				/>
			</div>
		</LandingSection>
	);
}
