import React from 'react';
import LandingSection from './LandingSection';
import { Code, FormInput, Key } from 'lucide-react';
import { ExternalLink } from 'lucide-react';
import FeatureCardTabs from './tabs/FeatureCardTabs';

const data = [
	{
		title: 'Languages',
		description: 'Python, Typescript, Go, Bash scripts with any dependencies',
		icon: Code,
		caption: 'Windmill supports Typescript, Python, Go and Bash scripts',
		video: {
			videoSrc: '/videos/languages.mp4',
			videoLength: 21
		}
	},

	{
		title: 'Autogenerated UI ',
		description:
			"Share your app with non-technical users without spending time building the UI. It's automatically generated from script parameters, and customizable.",
		icon: FormInput,
		caption: 'UI is autogenerated from script parameters',
		video: {
			videoSrc: '/videos/autogenerated-ui.mp4',
			videoLength: 26
		}
	},
	{
		title: 'Simple secret management',
		description:
			'Credentials and sensitive values are tightly permissioned and stored securely as secrets.',
		icon: Key,
		caption:
			'Secrets are stored securely and tightly permissioned, and can easily be inserted into scripts',
		video: {
			videoSrc: '/videos/secrets.mp4',
			videoLength: 44
		}
	}
];

const tabs = [
	{
		label: 'Script Editor',
		icon: Code,
		id: 'script',
		data
	}
];

export default function ScriptSection() {
	return (
		<LandingSection bgClass="bg-gradient-to-br from-white to-blue-50">
			<div className="flex flex-col gap-8 justify-center">
				<div className="flex flex-col gap-2">
					<h1 className="tracking-tight leading-tight text-left font-bold text-transparent bg-clip-text bg-gradient-to-br from-blue-400 to-blue-600">
						Scripts
					</h1>
					<h2 className="text-gray-600 text-2xl font-semibold">
						No overhead, scalable, self-hostable FaaS
					</h2>
				</div>

				<span className="text-lg text-gray-600 max-w-3xl">
					Develop and maintain scripts from our feature-complete webeditor or use your own IDE and
					deploy from Github. Upskill your less technical teammates. It's easier to learn writing
					useful scripts with Windmill.
				</span>

				<FeatureCardTabs tabs={tabs} initialTabId="script-editor" color='blue' />
				<div className="flex">
					<a
						type="button"
						href="https://hub.windmill.dev/"
						target="_blank"
						className="inline-flex items-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
					>
						Explore scripts on the Hub
						<ExternalLink className="ml-2 h-5" />
					</a>
				</div>
			</div>
		</LandingSection>
	);
}
