import React from 'react';
import LandingSection from '../landing/LandingSection';
import FeatureCard from '../landing/FeatureCard';
import { Code, FormInput, Key } from 'lucide-react';
import { SiGnubash, SiGo, SiPython, SiTypescript } from 'react-icons/si/index';
import { ExternalLink } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import FeatureCardTabs from '../landing/tabs/FeatureCardTabs';

const data = [
	{
		title: 'Languages',
		description: 'Python, Typescript, Go, Bash scripts with any dependencies',
		icon: Code,
		videoLength: 21,
		caption: 'Windmill supports Typescript, Python, Go and Bash scripts',
		videoSrc: '/videos/languages.mp4'
	},

	{
		title: 'Autogenerated UI ',
		description:
			"Share your app with non-technical users without spending time building the UI. It's automatically generated from script parameters, and customizable.",
		icon: FormInput,
		videoLength: 26,
		caption: 'UI is autogenerated from script parameters',
		videoSrc: '/videos/autogenerated-ui.mp4'
	},
	{
		title: 'Simple secret management',
		description:
			'Credentials and sensitive values are tightly permissioned and stored securely as secrets.',
		icon: Key,
		videoLength: 44,
		caption:
			'Secrets are stored securely and tightly permissioned, and can easily be inserted into scripts',
		videoSrc: '/videos/secrets.mp4'
	}
];

const tabs = [
	{
		label: 'Script Editor',
		icon: Code,
		id: 'script',
		children: <div />
	}
];

export default function ScriptSection() {
	const [selectedIndex, setSelectedIndex] = React.useState(0);

	let timeout = null;

	React.useEffect(() => {
		timeout = setTimeout(() => {
			setSelectedIndex((selectedIndex + 1) % data.length);
		}, data[selectedIndex].videoLength * 1000);
	}, [selectedIndex]);

	return (
		<LandingSection bgClass="bg-gradient-to-br from-white to-blue-50">
			<div className="flex flex-col gap-8 justify-center">
				<div className="flex flex-col gap-2">
					<h1 className="tracking-tight leading-tight text-left font-bold text-transparent bg-clip-text bg-gradient-to-br from-blue-400 to-blue-600">
						Scripts
					</h1>
					<h2 className="text-gray-600 text-2xl font-semibold">
						No overhead, scalable, self-hostable FaaS
					</h2>
				</div>

				<span className="text-lg text-gray-600 max-w-3xl">
					Develop and maintain scripts from our feature-complete webeditor or use your own IDE and
					deploy from Github. Upskill your less technical teammates. It's easier to learn writing
					useful scripts with Windmill.
				</span>

				<div className="grid grid-cols-1 lg:grid-cols-3 gap-8 w-full">
					<div className="grid grid-cols-1 sm:grid-cols-1 gap-4">
						{data.map((item, index) => (
							<button
								onClick={() => {
									clearTimeout(timeout);
									setSelectedIndex(index);
								}}
								key={index}
							>
								<FeatureCard
									title={item.title}
									color="blue"
									Icon={item.icon}
									index={index}
									selected={index === selectedIndex}
								>
									{item.description}
								</FeatureCard>
							</button>
						))}
					</div>

					<div className=" col-span-2 relative h-full flex items-center">
						<AnimatePresence mode="sync">
							<motion.div
								key={selectedIndex}
								initial={{ opacity: 0, scale: 0.5 }}
								animate={{ opacity: 1, scale: 1 }}
								exit={{ opacity: 0, scale: 0.5, position: 'absolute' }}
							>
								<div class="flex flex-col w-full gap-2 italic justify-center">
									<video
										className="border-2 h-min rounded-xl object-cover w-full"
										autoPlay
										loop
										src={data[selectedIndex].videoSrc}
									/>
									<span className="text-gray-500 text-center w-full text-sm">
										{data[selectedIndex].caption}
									</span>
								</div>
							</motion.div>
						</AnimatePresence>
					</div>
				</div>
				<div className="flex">
					<a
						type="button"
						href="https://hub.windmill.dev/"
						target="_blank"
						className="inline-flex items-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
					>
						Explore scripts on the Hub
						<ExternalLink className="ml-2 h-5" />
					</a>
				</div>
			</div>
		</LandingSection>
	);
}
