/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	tutorialSidebar: [
		'intro',
		{
			type: 'category',
			label: 'Getting Started',
			items: [{ type: 'autogenerated', dirName: 'getting_started' }],
			collapsed: false
		},
		{
			type: 'category',
			label: 'How-Tos',
			items: [{ type: 'autogenerated', dirName: 'how-tos' }],
			collapsed: false
		},
		{
			type: 'category',
			label: 'App Editor',
			items: [{ type: 'autogenerated', dirName: 'apps' }],
			collapsed: false
		},
		{
			type: 'category',
			label: 'Flow Editor',
			items: [{ type: 'autogenerated', dirName: 'flows' }],
			collapsed: false
		},
		{
			type: 'category',
			label: 'Integration Tutorials',
			items: [{ type: 'autogenerated', dirName: 'integrations' }],
			collapsed: false
		},
		'reference',
		'benchmark',
		'openflow',
		'contributors_guide'
	]
};

module.exports = sidebars;
