import React, { useEffect } from 'react';
import './CardStyles.css'; // Assuming the css is stored in a file called CardStyles.css
import classNames from 'classnames';
import { LucideAccessibility } from 'lucide-react';

const Card = ({ Icon, title, subtitle, gridArea }) => {
	const cardStyle = gridArea ? gridArea : '';

	return (
		<div className={classNames('card border shadow-none hover:shadow-sm transition-all', gridArea)}>
			<div className="card-content">
				<div className="card-image">
					<video
						className="border-2 rounded-xl object-cover w-full h-full"
						autoPlay
						loop
						src={'/videos/autogenerated-ui.mp4'}
					/>
				</div>
				<div className="py-4 px-2">
					<div className="flex flex-row gap-4">
						<Icon />

						<div className="">
							<div className="text-md font-bold mb-2">{title}</div>
							<div className="text-sm">{subtitle}</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
};

const CardsContainer = () => {
	useEffect(() => {
		const mouseMoveHandler = (e) => {
			for (const card of document.getElementsByClassName('card')) {
				const rect = card.getBoundingClientRect(),
					x = e.clientX - rect.left,
					y = e.clientY - rect.top;

				card.style.setProperty('--mouse-x', `${x}px`);
				card.style.setProperty('--mouse-y', `${y}px`);
			}
		};

		document.getElementById('cards').addEventListener('mousemove', mouseMoveHandler);

		// Cleanup on unmount
		return () => {
			document.getElementById('cards').removeEventListener('mousemove', mouseMoveHandler);
		};
	}, []);

	return (
		<div className="flex justify-center items-center h-full flex-col gap-2">
			<div id="cards">
				{[...Array(6)].map((_, i) => (
					<Card
						icon="fa-unicorn"
						title="Unicorns"
						subtitle="A single corn. Er, I mean horn."
						Icon={LucideAccessibility}
						gridArea={i === 0 ? 'col-span-1 row-span-6' : i === 5 ? 'col-span-3 row-span-4' : ''}
					/>
				))}
			</div>
		</div>
	);
};

export default CardsContainer;
