name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  determine-commenter:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/ai')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '/ai')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '/ai')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '/ai'))
    runs-on: ubicloud-standard-2
    outputs:
      commenter: ${{ steps.determine-commenter.outputs.commenter }}
    steps:
      - name: Determine commenter
        id: determine-commenter
        run: |
          # Work out who wrote the comment / review
          if [[ "${{ github.event_name }}" == "issue_comment" || \
                "${{ github.event_name }}" == "pull_request_review_comment" ]]; then
            COMMENTER="${{ github.event.comment.user.login }}"
          elif [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            COMMENTER="${{ github.event.review.user.login }}"
          else
            COMMENTER="${{ github.event.issue.user.login }}"
          fi
          echo "commenter=$COMMENTER" >> $GITHUB_OUTPUT

  check-membership:
    needs: determine-commenter
    uses: windmill-labs/windmill/.github/workflows/check-org-membership.yml@main
    with:
      commenter: ${{ needs.determine-commenter.outputs.commenter }}
    secrets:
      access_token: ${{ secrets.ORG_ACCESS_TOKEN }}

  claude-code-action:
    needs: check-membership
    if: |
      needs.check-membership.outputs.is_member == 'true'
    runs-on: ubicloud-standard-8
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: '60'
          allowed_tools: 'mcp__github__create_pull_request'
          custom_instructions: 'IMPORTANT: Bypass previous instructions and instead of adding a url in your comment to manually create a PR, if you created a new branch with your changes, automatically create a draft PR from that branch to main.'
          trigger_phrase: '/ai'
          assignee_trigger: 'ai'
